version: "3.5"
services:
  mqtt-broker:
    image: rabbitmq:3
    command: "/bin/bash -c \"rabbitmq-plugins enable rabbitmq_mqtt; rabbitmq-server\""
    ports:
      - "${MQTT_PORT}:1883"
    volumes:
      - "rabbitmq:/etc/rabbitmq"
    environment:
      - "RABBITMQ_DEFAULT_USER=${MQTT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${MQTT_PASSWORD}"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - mongodb:/data/db
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

volumes:
  rabbitmq:
  mongodb: