site_name: Gatway Documentation
site_url: "https://bchwtz.github.io/bchwtz-gateway/"

theme:
  name: "material"
  features:
    - content.code.annotate

plugins:
  - mkdocstrings
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables


nav:
  - index.md
  - Reference:
    - Gateway Library:
      - bluetooth-python-library/gateway_ref.md
      - bluetooth-python-library/config_ref.md
      - bluetooth-python-library/hub_ref.md
      - bluetooth-python-library/tag_ref.md
      - bluetooth-python-library/sensor_ref.md
      - bluetooth-python-library/ble_conn_ref.md
    - Global Architecture:
      - mqtt_messages.md
    - go-services/cli_ref.md
  - Demos: 
    - Overview: demos_overview.md
    - Analyse Heartbeat: analyse_heatbeats_ref.md
    - Time Demo: current_time_demo_ref.md
    - Heartbeat Demo: get_set_heartbeat_ref.md
  - Tests:
    - Test Documentation: test-documentation.md
    - Hub Tests: hub_test_ref.md
    - Tag Test: tag_test_ref.md
    - Tag Config Tests: tag_config_test_ref.md
  - git_installation_on_raspberry.md
  - MKDocs: documentation_ref.md
  - readme.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bchwtz/