site_name: Gatway Documentation
site_url: "https://bchwtz.github.io/bchwtz-gateway/"

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
  - Reference:
    - gateway_ref.md
    - config_ref.md
    - hub_ref.md
    - tag_ref.md
    - sensor_ref.md
    - ble_conn_ref.md
  - Demos: 
    - Overview: demos_overview.md
    - Analyse Heartbeat: analyse_heatbeats_ref.md
    - Time Demo: current_time_demo_ref.md
    - Heartbeat Demo: get_set_heartbeat_ref.md
  - Tests:
    - Test Documentation: test-documentation.md
    - Hub Tests: hub_test_ref.md
    - Tag Test: tag_test_ref.md
    - Tag Config Tests: tag_config_test_ref.md
  - git_installation_on_raspberry.md
  - MKDocs: documentation_ref.md
  - readme.md
