site_name: Gateway Documentation
site_url: "https://bchwtz.github.io/bchwtz-gateway/"

theme:
  name: "material"
  features:
    - content.code.annotate
    - content.code.copy

plugins:
  - mkdocstrings
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables


nav:
  - Introduction: index.md
  - Getting Started:
    - user_setup.md
    - developer_setup.md
    - go_cli.md
  - Reference:
    - Gateway Library:
      - bluetooth-python-library/gateway_ref.md
      - bluetooth-python-library/config_ref.md
      - bluetooth-python-library/hub_ref.md
      - bluetooth-python-library/tag_ref.md
      - bluetooth-python-library/sensor_ref.md
      - bluetooth-python-library/ble_conn_ref.md
    - Global Architecture:
      - global_architecture/mqtt_messages.md
      - global_architecture/docker_architecture.md
    - Additional Microservices:
      - CLI: go-services/cli_ref.md
      - Dumper: go-services/dumper_ref.md
      - Go Library Packages:
        - gateway-package: go-services/gateway_ref.md
        - model-package: go-services/model_ref.md
        - commandinterface-package: go-services/commandinterface_ref.md
    - Examples:
      - Demos: 
        - Overview: demos_overview.md
        - Analyse Heartbeat: analyse_heartbeats_ref.md
        - Time Demo: current_time_demo_ref.md
        - Heartbeat Demo: get_set_heartbeat_ref.md
        - Acceleration Log Demo: demo_get_acc_log_ref.md
      - Tests:
        - Test Documentation: bluetooth-python-library/test-documentation.md
        - Hub Tests: bluetooth-python-library/hub_test_ref.md
        - Tag Test: bluetooth-python-library/tag_test_ref.md
        - Tag Config Tests: bluetooth-python-library/tag_config_test_ref.md
    - Further tutorials:
      - git_installation_on_raspberry.md
      - MKDocs: documentation_ref.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bchwtz/