site_name: Gatway Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Gateway Documentation: index.md
  - tutorials.md
  - Reference:
    - gateway_ref.md
    - config_ref.md
    - hub_ref.md
    - tag_ref.md
    - sensor_ref.md
    - ble_conn_ref.md
  - Demos: 
    - demos_overview.md
    - analyse_heatbeats_ref.md
    - current_time_demo_ref.md
    - get_set_heartbeat_ref.md
  - explanation.md
  - test-documentation.md
  - git_installation_on_raspberry.md
  - link_to_readme.md
