site_name: Gatway Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - introduction.md
  - Reference:
    - gateway_ref.md
    - config_ref.md
    - hub_ref.md
    - tag_ref.md
    - sensor_ref.md
    - ble_conn_ref.md
  - Demos: 
    - Overview: demos_overview.md
    - Analyse Heartbeat: analyse_heatbeats_ref.md
    - Time Demo: current_time_demo_ref.md
    - Heartbeat Demo: get_set_heartbeat_ref.md
  - explanation.md
  - test-documentation.md
  - git_installation_on_raspberry.md
  - Documentation: documentation_ref.md
  - readme.md
