site_name: Gatway Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Gateway Documentation: index.md
  - introduction.md
  - Reference:
    - gateway_ref.md
    - config_ref.md
    - hub_ref.md
    - tag_ref.md
    - sensor_ref.md
    - ble_conn_ref.md
  - Demos: 
    - demos_overview.md
    - analyse_heatbeats_ref.md
    - current_time_demo_ref.md
    - get_set_heartbeat_ref.md
  - explanation.md
  - test-documentation.md
  - git_installation_on_raspberry.md
  - link_to_readme.md
