# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, mf-deployment ]
  pull_request:
    branches: [ main, mf-deployment ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      working-directory: ./deployments
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $secrets.MF_AUTH_DB_PASS && docker-compose build
        working-directory: ${{env.working-directory}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        working-directory: ${{env.working-directory}}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy:
    needs: build
    runs-on: deploy
    env:
      working-directory: ./deployments
      env-file: .env
      MF_AUTH_DB_PASS: ${{ secrets.MF_AUTH_DB_PASS }}
      MF_USERS_DB_PASS: ${{ secrets.MF_USERS_DB_PASS }}
      MF_USERS_ADMIN_PASSWORD: ${{ secrets.MF_USERS_ADMIN_PASSWORD }}
      MF_EMAIL_PASSWORD: ${{ secrets.MF_EMAIL_PASSWORD }}
      MF_THINGS_DB_PASS: ${{ secrets.MF_THINGS_DB_PASS }}
      MF_THINGS_ES_PASS: ${{ secrets.MF_THINGS_ES_PASS }}
      MF_MQTT_ADAPTER_ES_PASS: ${{ secrets.MF_MQTT_ADAPTER_ES_PASS }}
      MF_BOOTSTRAP_DB_PASS: ${{ secrets.MF_BOOTSTRAP_DB_PASS }}
      MF_PROVISION_PASS: ${{ secrets.MF_PROVISION_PASS }}
      MF_OPCUA_ADAPTER_ROUTE_MAP_PASS: ${{ secrets.MF_OPCUA_ADAPTER_ROUTE_MAP_PASS }}
      MF_INFLUX_WRITER_DB_PASS: ${{ secrets.MF_INFLUX_WRITER_DB_PASS }}
      MF_INFLUX_READER_DB_PASS: ${{ secrets.MF_INFLUX_READER_DB_PASS }}
      MF_TWINS_CACHE_PASS: ${{ secrets.MF_TWINS_CACHE_PASS }}

    steps:
      - uses: actions/checkout@v2
      - name: docker-pull
        run: /usr/local/bin/docker-compose pull
        working-directory: ${{env.working-directory}}

      
      - name: load-env
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ${{ env.env-file }}
        working-directory: ${{env.working-directory}}
      - name: docker up
        working-directory: ${{env.working-directory}}
        run: /usr/local/bin/docker-compose up -d