name: docs
on:
  pull_request:
    branches:
      - main
      - refactoring-and-new-design
  push:
    branches:
      - main
      - refactoring-and-new-design
jobs:
  deploy:
    runs-on: fhswf
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material mkdocstrings[python]
      - run: mkdocs gh-deploy --force --clean --verbose